Word Embedding Techniques using Embedding layer in Keras

In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
sen=['the glass of milk',
     'the glass of juice',
     'the cup of tea',
     'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [4]:
print(sen)

['the glass of milk', 'the glass of juice', 'the cup of tea', 'I am a good boy', 'I am a good developer', 'understand the meaning of words', 'your videos are good']


In [5]:
voc_size=10000 #vocabulary size

One Hot Represemtation

In [10]:
one_hot_repr=[one_hot(words,voc_size) for words in sen]
print(one_hot_repr)

[[4892, 9028, 4759, 1415], [4892, 9028, 4759, 8203], [4892, 3158, 4759, 5847], [784, 9027, 2192, 2414, 5687], [784, 9027, 2192, 2414, 2737], [1434, 4892, 7436, 4759, 925], [3445, 7938, 3585, 2414]]


Word Embedding Representation

In [12]:
from tensorflow.keras.models import  Sequential
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [14]:
import numpy as np


In [17]:
sen_lenghth=8
embedded_docs=pad_sequences (one_hot_repr,maxlen=sen_lenghth,padding='pre')
print(embedded_docs)

[[   0    0    0    0 4892 9028 4759 1415]
 [   0    0    0    0 4892 9028 4759 8203]
 [   0    0    0    0 4892 3158 4759 5847]
 [   0    0    0  784 9027 2192 2414 5687]
 [   0    0    0  784 9027 2192 2414 2737]
 [   0    0    0 1434 4892 7436 4759  925]
 [   0    0    0    0 3445 7938 3585 2414]]


In [19]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sen_lenghth))

In [20]:
model.compile()

In [21]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [22]:
print(model.predict(embedded_docs))

[[[ 2.52942778e-02  2.47047283e-02 -2.13099364e-02  1.71653070e-02
    4.13685478e-02  9.39375162e-03 -4.12865765e-02  2.33911760e-02
    8.96173716e-03  3.74437086e-02]
  [ 2.52942778e-02  2.47047283e-02 -2.13099364e-02  1.71653070e-02
    4.13685478e-02  9.39375162e-03 -4.12865765e-02  2.33911760e-02
    8.96173716e-03  3.74437086e-02]
  [ 2.52942778e-02  2.47047283e-02 -2.13099364e-02  1.71653070e-02
    4.13685478e-02  9.39375162e-03 -4.12865765e-02  2.33911760e-02
    8.96173716e-03  3.74437086e-02]
  [ 2.52942778e-02  2.47047283e-02 -2.13099364e-02  1.71653070e-02
    4.13685478e-02  9.39375162e-03 -4.12865765e-02  2.33911760e-02
    8.96173716e-03  3.74437086e-02]
  [ 2.72692926e-02  6.81094080e-03 -4.56490368e-03  4.37722318e-02
   -4.95522395e-02  3.31793316e-02 -3.70818749e-02  3.73673700e-02
    3.48102115e-02  4.09172289e-02]
  [ 2.96797603e-03 -1.51736960e-02 -2.12899595e-03 -4.91658561e-02
    2.68987529e-02 -4.09705862e-02  3.31300162e-02  4.00885679e-02
   -4.17953841e-

In [23]:
print(embedded_docs[0])

[   0    0    0    0 4892 9028 4759 1415]


In [24]:
print(model.predict(embedded_docs)[0])

[[ 0.02529428  0.02470473 -0.02130994  0.01716531  0.04136855  0.00939375
  -0.04128658  0.02339118  0.00896174  0.03744371]
 [ 0.02529428  0.02470473 -0.02130994  0.01716531  0.04136855  0.00939375
  -0.04128658  0.02339118  0.00896174  0.03744371]
 [ 0.02529428  0.02470473 -0.02130994  0.01716531  0.04136855  0.00939375
  -0.04128658  0.02339118  0.00896174  0.03744371]
 [ 0.02529428  0.02470473 -0.02130994  0.01716531  0.04136855  0.00939375
  -0.04128658  0.02339118  0.00896174  0.03744371]
 [ 0.02726929  0.00681094 -0.0045649   0.04377223 -0.04955224  0.03317933
  -0.03708187  0.03736737  0.03481021  0.04091723]
 [ 0.00296798 -0.0151737  -0.002129   -0.04916586  0.02689875 -0.04097059
   0.03313002  0.04008857 -0.04179538  0.01721108]
 [ 0.0012341  -0.02571939  0.04665078  0.04575608  0.00324961 -0.0312263
  -0.04273526 -0.02483882 -0.04238409  0.04673855]
 [-0.01640389 -0.02643433  0.00921813 -0.01802598 -0.04190677 -0.04569359
   0.02568657 -0.04614621 -0.02817943 -0.00983153]]
